log_dir: "/data8/master_dataset_model_zhangyuqiang/StyleTTS/models/f0"
save_freq: 10
device: "cuda"
epochs: 100
batch_size: 64
pretrained_model: ""
train_data: "Data/train_list_aishell3.txt"
val_data: "Data/eval_list_aishell3.txt"
fea_dir: "/data8/master_dataset_model_zhangyuqiang/StyleTTS/datasets/fea_f0"
num_workers: 16

  
optimizer_params:
  lr: 0.0003
  
loss_params:
  lambda_f0: 0.1
  
